Hide wind speed and direction
decompil3d/lovelace-hourly-weather pull request #190
Opened 2022-10-20 14:03 UTC by akropp

Wanted to be able to only show the wind speed (without the direction).  For completeness, added two flags: hide_wind_speed and hide_wind_direction.  They work in concert with show_wind, and default to false (so the existing behavior).

2022-10-20 14:21 UTC, decompil3d requested changes
Thanks so much for your contribution! I like the idea of being able to show only wind speed or direction. I think that we can achieve the same result without adding more flags though.

Can you please refactor to make `show_wind` take these values:

- `true`: show both wind speed and direction
- `false`: show neither speed nor direction
- `'speed'`: show only wind speed
- `'direction'`: show only wind direction

Then, in the editor UI, you can just replace the existing wind switch with a drop-down or similar to choose from these options.

What do you think?

2022-10-20 16:31 UTC, akropp commented
Cool.  Good idea.  I didn't really like the separate flags thing either.

--Adam


On Thu, Oct 20, 2022 at 10:21 AM Jonathan Keslin ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks so much for your contribution! I like the idea of being able to
> show only wind speed or direction. I think that we can achieve the same
> result without adding more flags though.
>
> Can you please refactor to make show_wind take these values:
>
>    - true: show both wind speed and direction
>    - false: show neither speed nor direction
>    - 'speed': show only wind speed
>    - 'direction': show only wind direction
>
> Then, in the editor UI, you can just replace the existing wind switch with
> a drop-down or similar to choose from these options.
>
> What do you think?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/decompil3d/lovelace-hourly-weather/pull/190#pullrequestreview-1149358001>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHIXJVNRWF24AU6XEV6LS2DWEFIOPANCNFSM6AAAAAARKGCEBY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-02 21:23 UTC, decompil3d requested changes
Played with it a little and I do see the editor behavior you described. However, that same behavior happens on the `entity` field and that logic comes from the base custom card template repo. So, I'm inclined to just let it be as-is. If someone really wants to manage their cards in YAML and needs to mess with this field, then they can either use the dashboard-level YAML editor, or they can compose elsewhere and paste in to avoid the partial text validation problem.

Just a small refactor request for how you render the wind elements and I think we'll be good to go.

2022-11-02 21:23 UTC, decompil3d commented on src/weather-bar.ts
>        const { windSpeed, windDirection } = this.wind[i];
```suggestion
      const { windSpeed, windDirection } = this.wind[i];

      const wind: TemplateResult[] = [];
      if (showWindSpeed) wind.push(html`${windSpeed}`);
      if (showWindSpeed && showWindDirection) wind.push(html`<br>`);
      if (showWindDirection) wind.push(html`${windDirection}`);

```

2022-11-02 21:23 UTC, decompil3d commented on src/weather-bar.ts
> +                  : null }</div>
```suggestion
            <div class="wind">${wind}</div>
```

2022-11-03 14:58 UTC, akropp commented
Sounds good.

2022-11-03 21:17 UTC, decompil3d approved these changes

2022-11-03 21:17 UTC, merged